language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - npm i -g npm@latest
  - npm run foo
  - phantomjs --version
before_script:
  - echo now before script
after_script: 
  - echo now test finished
