language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - npm i -g npm@latest
before_script:
  - echo now before script
after_script: 
  - echo now karma
  - karma start
  - echo now test finished
